
version: '3'
services:

  # nats-server:
  #   image: nats:latest
  #   restart: always
  #   ports:
  #     - 4222:4222
  #     - 8222:8222
  #     - 6222:6222
  #   networks:
  #     - ia-backend
  #   command: ["-c", "/etc/nats-server.conf"]
  #   volumes:
  #     - ./nats-server.conf:/etc/nats-server.conf

  db:
    container_name: db
    image: postgres:17.2-alpine3.21
    restart: always
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
    networks:
      - ia-backend

  # client-gateway:
  #   build:
  #     context: ./client-gateway
  #     args:
  #       - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   ports:
  #     - ${PORT_CLIENT_GATEWAY}:3000
  #   restart: always
  #   volumes:
  #     - ./client-gateway/src:/usr/src/app/src
  #   environment:
  #     - PORT=3000
  #     - NODE_ENV=${NODE_ENV}
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   networks:
  #     - ia-backend

  # auth-ms:
  #   build:
  #     context: ./auth-ms
  #     args:
  #       - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   restart: always
  #   depends_on:
  #     - nats-server
  #     - db
  #     - client-gateway
  #   volumes:
  #     - ./auth-ms/src:/usr/src/app/src
  #   environment:
  #     - PORT=3001
  #     - NODE_ENV=${NODE_ENV}
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - JWT_SECRET=${JWT_SECRET}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   networks:
  #     - ia-backend

  # user-ms:
  #   build:
  #     context: ./user-ms
  #     args:
  #       - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   restart: always
  #   depends_on:
  #     - nats-server
  #     - db
  #     - client-gateway
  #   volumes:
  #     - ./user-ms/src:/usr/src/app/src
  #   environment:
  #     - PORT=3002
  #     - NODE_ENV=${NODE_ENV}
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   networks:
  #     - ia-backend

networks:
  ia-backend:
    driver: bridge
